version: '3.8'

services:
  # FastAPI service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m ragaman.main --mode api
    ports:
      - "${HOST_PORT:-8000}:8000"
    volumes:
      - ./notes.db:/app/notes.db
      - ./src:/app/src  # For development mode with live reload
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_NAME=${APP_NAME:-Ragaman API}
      - API_VERSION=${API_VERSION:-v1}
      - DB_PATH=${DB_PATH:-notes.db}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - HOST=0.0.0.0  # Bind to all interfaces in Docker
      - PORT=8000
    restart: unless-stopped

  # MCP HTTP service
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m ragaman.main --mode mcp --transport http
    ports:
      - "${MCP_HOST_PORT:-8080}:8080"
    volumes:
      - ./notes.db:/app/notes.db  # Share the same database as the API
      - ./src:/app/src  # For development mode with live reload
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_NAME=${APP_NAME:-Ragaman API}
      - DB_PATH=${DB_PATH:-notes.db}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - MCP_NAME=${MCP_NAME:-ragaman}
      - MCP_TRANSPORT=http
      - MCP_HTTP_PORT=8080
    restart: unless-stopped